name: CI - ExecuÃ§Ã£o de Testes Automatizados
run-name: Testes de CI com Robot Framework
on: [push]
   
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: [testes_web, testes_API, trabalhando_estruturas, trabalhando_variaveis_escopos_argumentos]  # Adicione os tipos de teste que vocÃª deseja executar aqui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python 3.12.0
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.0'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          pip install -U -r requirements.txt
      
      - name: Run tests
        run: |
          if [ "${{ matrix.test_type }}" == "testes_web" ]; then
            robot -d ./testes_web/resultados-testes-CI -v HEADLESS:true -v BROWSER:chrome -i CT01 -i CT02 testes_web/tests
          elif [ "${{ matrix.test_type }}" == "testes_API" ]; then
            robot -d ./testes_API/resultados-testes-CI testes_API/tests
          elif [ "${{ matrix.test_type }}" == "trabalhando_estruturas" ]; then
            robot -d ./trabalhando_estruturas/resultados-testes-CI trabalhando_estruturas/tests
          elif [ "${{ matrix.test_type }}" == "trabalhando_variaveis_escopos_argumentos" ]; then
            robot -d ./trabalhando_variaveis_escopos_argumentos/resultados-testes-CI trabalhando_variaveis_escopos_argumentos/tests
          fi

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.test_type }}-results
          path: ./${{ matrix.test_type }}/resultados-testes-CI
          if-no-files-found: ignore
          retention-days: 2
  
      - name: Download results
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.test_type }}-results
          path: ./resultados/${{ matrix.test_type }}

      - name: Debug - Verificar arquivos baixados
        if: always()
        run: ls -R ./resultados/${{ matrix.test_type }} || echo "Nenhum arquivo baixado!"
      
      - name: Publicar SumÃ¡rio no GitHub Actions
        if: always()
        run: |
          echo "## ðŸ“Š Resultados dos Testes Automatizados ðŸš€" >> $GITHUB_STEP_SUMMARY
          echo "- Tipo de teste: **${{ matrix.test_type }}**" >> $GITHUB_STEP_SUMMARY
          echo "- Status da execuÃ§Ã£o: **${{ job.status == 'success' && 'âœ… Sucesso' || 'âŒ Falha' }}**" >> $GITHUB_STEP_SUMMARY